"""add postal_code weather_area relationship

Revision ID: 182a940dbd65
Revises: cecc35b1ffe3
Create Date: 2025-07-18 05:58:23.148980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '182a940dbd65'
down_revision: Union[str, None] = 'cecc35b1ffe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crop', 'aliases',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.add_column('postal_code', sa.Column('weather_area_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'postal_code', 'weather_area', ['weather_area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'postal_code', type_='foreignkey')
    op.drop_column('postal_code', 'weather_area_id')
    op.alter_column('crop', 'aliases',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###
