"""create crop table

Revision ID: 38f7b52b1431
Revises: 
Create Date: 2025-07-18 03:18:29.489161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '38f7b52b1431'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aliases', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_category'), 'crop', ['category'], unique=False)
    op.create_index(op.f('ix_crop_code'), 'crop', ['code'], unique=True)
    op.create_index(op.f('ix_crop_name'), 'crop', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crop_name'), table_name='crop')
    op.drop_index(op.f('ix_crop_code'), table_name='crop')
    op.drop_index(op.f('ix_crop_category'), table_name='crop')
    op.drop_table('crop')
    # ### end Alembic commands ###
