"""create weather_area table

Revision ID: 3be52d1a968c
Revises: 5a2d9a52c0dd
Create Date: 2025-07-18 05:22:20.176384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3be52d1a968c'
down_revision: Union[str, None] = '5a2d9a52c0dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefecture', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_area_city'), 'weather_area', ['city'], unique=False)
    op.create_index(op.f('ix_weather_area_prefecture'), 'weather_area', ['prefecture'], unique=False)
    op.create_index(op.f('ix_weather_area_region'), 'weather_area', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_area_region'), table_name='weather_area')
    op.drop_index(op.f('ix_weather_area_prefecture'), table_name='weather_area')
    op.drop_index(op.f('ix_weather_area_city'), table_name='weather_area')
    op.drop_table('weather_area')
    # ### end Alembic commands ###
