"""create postal_code table

Revision ID: 5a2d9a52c0dd
Revises: 38f7b52b1431
Create Date: 2025-07-18 05:06:40.193472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5a2d9a52c0dd'
down_revision: Union[str, None] = '38f7b52b1431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postal_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prefecture', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('town', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postal_code_city'), 'postal_code', ['city'], unique=False)
    op.create_index(op.f('ix_postal_code_postal_code'), 'postal_code', ['postal_code'], unique=False)
    op.create_index(op.f('ix_postal_code_prefecture'), 'postal_code', ['prefecture'], unique=False)
    op.create_index(op.f('ix_postal_code_town'), 'postal_code', ['town'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_postal_code_town'), table_name='postal_code')
    op.drop_index(op.f('ix_postal_code_prefecture'), table_name='postal_code')
    op.drop_index(op.f('ix_postal_code_postal_code'), table_name='postal_code')
    op.drop_index(op.f('ix_postal_code_city'), table_name='postal_code')
    op.drop_table('postal_code')
    # ### end Alembic commands ###
