"""Add difficulty and difficulty_reason columns to crop table

Revision ID: add_crop_difficulty
Revises: cecc35b1ffe3
Create Date: 2025-07-18 22:06:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_crop_difficulty'
down_revision = 'ae102732afc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crop', sa.Column('difficulty', sa.Integer(), nullable=True))
    op.add_column('crop', sa.Column('difficulty_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crop', 'difficulty_reason')
    op.drop_column('crop', 'difficulty')
    # ### end Alembic commands ###