"""Add user_crops many-to-many table

Revision ID: add_user_crops_table
Revises: convert_table_names_to_plural
Create Date: 2025-07-19 13:10:00.000000

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = 'add_user_crops_table'
down_revision = 'convert_table_names_to_plural'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create user_crops table
    op.create_table('user_crops',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('crop_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_crops_crop_id'), 'user_crops', ['crop_id'], unique=False)
    op.create_index(op.f('ix_user_crops_user_id'), 'user_crops', ['user_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_user_crops_user_id'), table_name='user_crops')
    op.drop_index(op.f('ix_user_crops_crop_id'), table_name='user_crops')
    op.drop_table('user_crops')
    
    # ### end Alembic commands ###