"""Convert table names to plural form

Revision ID: convert_table_names_to_plural
Revises: remove_city_from_weather_area
Create Date: 2025-07-19 12:40:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'convert_table_names_to_plural'
down_revision = '6002a4af4dc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Rename tables to plural form
    op.rename_table('crop', 'crops')
    op.rename_table('weather_area', 'weather_areas')
    op.rename_table('postal_code', 'postal_codes')
    op.rename_table('crop_weather_area', 'crop_weather_areas')
    
    # Foreign key constraints will be automatically updated by PostgreSQL
    # when renaming tables, so no manual constraint updates needed
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Rename tables back to singular form
    op.rename_table('crops', 'crop')
    op.rename_table('weather_areas', 'weather_area')
    op.rename_table('postal_codes', 'postal_code')
    op.rename_table('crop_weather_areas', 'crop_weather_area')
    
    # Foreign key constraints will be automatically updated by PostgreSQL
    # when renaming tables back
    
    # ### end Alembic commands ###