"""Create crop_weather_area_difficulty table

Revision ID: create_crop_weather_difficulty
Revises: add_crop_difficulty
Create Date: 2025-07-18 22:15:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB


# revision identifiers, used by Alembic.
revision = 'create_crop_weather_difficulty'
down_revision = 'add_crop_difficulty'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_weather_area_difficulty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('weather_area_id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('difficulty_reasons', JSONB(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.id'], ),
    sa.ForeignKeyConstraint(['weather_area_id'], ['weather_area.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crop_id', 'weather_area_id', name='uq_crop_weather_difficulty')
    )
    op.create_index(op.f('ix_crop_weather_area_difficulty_crop_id'), 'crop_weather_area_difficulty', ['crop_id'], unique=False)
    op.create_index(op.f('ix_crop_weather_area_difficulty_weather_area_id'), 'crop_weather_area_difficulty', ['weather_area_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crop_weather_area_difficulty_weather_area_id'), table_name='crop_weather_area_difficulty')
    op.drop_index(op.f('ix_crop_weather_area_difficulty_crop_id'), table_name='crop_weather_area_difficulty')
    op.drop_table('crop_weather_area_difficulty')
    # ### end Alembic commands ###