"""Rename table crop_weather_area_difficulty to crop_weather_area

Revision ID: e88fa4277682
Revises: remove_city_from_weather_area
Create Date: 2025-07-19 01:42:37.394980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e88fa4277682'
down_revision: Union[str, None] = 'remove_city_from_weather_area'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename table while preserving data
    op.rename_table('crop_weather_area_difficulty', 'crop_weather_area')
    
    # Rename indexes
    op.drop_index('ix_crop_weather_area_difficulty_crop_id', table_name='crop_weather_area')
    op.drop_index('ix_crop_weather_area_difficulty_weather_area_id', table_name='crop_weather_area')
    op.create_index('ix_crop_weather_area_crop_id', 'crop_weather_area', ['crop_id'])
    op.create_index('ix_crop_weather_area_weather_area_id', 'crop_weather_area', ['weather_area_id'])
    
    # Rename unique constraint
    op.drop_constraint('uq_crop_weather_difficulty', 'crop_weather_area', type_='unique')
    op.create_unique_constraint('uq_crop_weather_area', 'crop_weather_area', ['crop_id', 'weather_area_id'])
    
    # Rename foreign key constraints
    op.drop_constraint('crop_weather_area_difficulty_crop_id_fkey', 'crop_weather_area', type_='foreignkey')
    op.drop_constraint('crop_weather_area_difficulty_weather_area_id_fkey', 'crop_weather_area', type_='foreignkey')
    op.create_foreign_key('crop_weather_area_crop_id_fkey', 'crop_weather_area', 'crop', ['crop_id'], ['id'])
    op.create_foreign_key('crop_weather_area_weather_area_id_fkey', 'crop_weather_area', 'weather_area', ['weather_area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverse the table rename process
    
    # Drop new constraints and indexes
    op.drop_constraint('crop_weather_area_crop_id_fkey', 'crop_weather_area', type_='foreignkey')
    op.drop_constraint('crop_weather_area_weather_area_id_fkey', 'crop_weather_area', type_='foreignkey')
    op.drop_constraint('uq_crop_weather_area', 'crop_weather_area', type_='unique')
    op.drop_index('ix_crop_weather_area_crop_id', table_name='crop_weather_area')
    op.drop_index('ix_crop_weather_area_weather_area_id', table_name='crop_weather_area')
    
    # Rename table back
    op.rename_table('crop_weather_area', 'crop_weather_area_difficulty')
    
    # Recreate original constraints and indexes
    op.create_index('ix_crop_weather_area_difficulty_crop_id', 'crop_weather_area_difficulty', ['crop_id'])
    op.create_index('ix_crop_weather_area_difficulty_weather_area_id', 'crop_weather_area_difficulty', ['weather_area_id'])
    op.create_unique_constraint('uq_crop_weather_difficulty', 'crop_weather_area_difficulty', ['crop_id', 'weather_area_id'])
    op.create_foreign_key('crop_weather_area_difficulty_crop_id_fkey', 'crop_weather_area_difficulty', 'crop', ['crop_id'], ['id'])
    op.create_foreign_key('crop_weather_area_difficulty_weather_area_id_fkey', 'crop_weather_area_difficulty', 'weather_area', ['weather_area_id'], ['id'])
    # ### end Alembic commands ###
