"""Remove city column from weather_area table

Revision ID: remove_city_from_weather_area
Revises: create_crop_weather_difficulty
Create Date: 2025-07-19 10:05:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'remove_city_from_weather_area'
down_revision = 'create_crop_weather_difficulty'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weather_area_city', table_name='weather_area')
    op.drop_column('weather_area', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_area', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_weather_area_city', 'weather_area', ['city'], unique=False)
    # ### end Alembic commands ###